name: Deploy and Build Frontend on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BIDDIUS_AWS_HOST }}
        username: ${{ secrets.BIDDIUS_AWS_SERVER_USER }}
        key: ${{ secrets.BIDDIUS_AWS_SERVER_KEY }}
        script: |

          cd /var/www/biddius/Auctora-Frontend || exit 1
          git reset --hard HEAD
          git clean -fd
          git pull --ff-only origin main
          npm install --legacy-peer-deps
          npm run build
          sudo rm -rf /var/www/biddius/html/*
          sudo cp -r dist/* /var/www/biddius/html/

          build_dir="/var/www/biddius/html/assets"

          css=$(ls $build_dir/index*.css | xargs -n1 basename)
          js=$(ls $build_dir/index*.js | xargs -n1 basename)
          
          sudo cat <<EOF > /etc/nginx/snippets/biddius-preload.conf
          add_header Link "</assets/$css>; rel=preload; as=style" always;
          add_header Link "</assets/$js>; rel=preload; as=script" always;
          EOF
          
          systemctl reload nginx
          
        shell: bash -l {0}
